---
name: automatic-merges

on:
  workflow_run:
    workflows: [ ci ] 
    types: completed

jobs:
  automatic-merge-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: find-triggering-pr
        uses: peternied/find-triggering-pr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peternied/discerning-merger@v2
        if: steps.find-triggering-pr.outputs.pr-number != null
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.find-triggering-pr.outputs.pr-number }}
          allowed-authors: |
            peternied
          allowed-files: |
            .gitignore